server:
  port: 9999
spring:
  application:
    name: zipkin-server
  sleuth:
    enabled: false
  datasource:
    name: zipkin
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zipkin?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456
    schema[0]: classpath:/zipkin.sql
    initialize: true
    continue-on-error: true
zipkin:
  storage:
    type: mysql